### ISSUE TITLE
Replace background map image with Edge CDN image

### ISSUE THREAD

**Issue by adamkdean** [edge/account#210]
See https://github.com/edge/account/blob/ffe606c6dd14c1a70b080e2ccf9826e4bc508fc7/src/views/Landing.vue#L18

**Comment by willgarrett64** [comment]
@adamkdean do you have url for the Edge CDN image for the background map?

**Comment by adamkdean** [comment]
Not currently no. You'll have to grab it from the top and stick it in the repo.

**Comment by annybs** [comment]
This issue has been set to Done but not actually closed. I have double checked and I believe it has been completed in or before https://github.com/edge/account/commit/d91df2301b9c01b8efb6d00204b0923ab41e2bc0 so I am going ahead and clearing this down.
