### ISSUE TITLE
Copy pasting from Google to MX value gives invalid domain error

### ISSUE THREAD

**Issue by adamkdean** [edge/account#232]
<img width="872" alt="image" src="https://github.com/edge/account/assets/1639527/2e579482-bfcb-4cb0-ae9c-c6fb79bfe911">

Error may be UI or may be API.

**Comment by annybs** [comment]
I have the feeling this is just because the target value is uppercased.

**Comment by annybs** [comment]
I've checked the backend behaviour and all domain-like values are validated as lowercase, so I think the solution is for UI to automatically lowercase any uppercase characters it encounters for applicable record types. Ideally this would be on the input itself but it might be simpler just to surreptitiously lowercase it when submitting to API. I'll have a look at the implementation and work out the best way forward.
