### ISSUE TITLE
Index doesn't always redirect established accounts to CDN

### ISSUE THREAD

**Issue by adamkdean** [edge/account#250]
![image](https://github.com/edge/account/assets/1639527/5db627d8-1089-4486-894a-5499f841ce59)

Sometimes it's just a blank page.

Previously there was an issue with index redirecting to cdn when it should have redirected to getting started, so we need to test with established accounts to ensure that works. Need to avoid the delays the previous, reverted fix introduced though.

**Comment by annybs** [comment]
Most recent patch to Index.vue specified the destination route incorrectly: https://github.com/edge/account/commit/0d99905f6ce5de1a216d4cb1be215f76f0b7304c

Fixed in v1.22.1
