### ISSUE TITLE
Table sorting

### ISSUE THREAD

**Issue by willgarrett64** [edge/account#58]
Servers
- created
- disk / ram / vcpus / badnwidth
- zone
- name
- status

Server backups
- created
- name
- size
- status

Server history (tasks)
- created
- event
- status

Domains
- created
- name
- records count
- status

Domain Records
- type
- name
- value
- ttl

Integrations
- created
- name
- domain
- requests
- traffic
- status

Purchases
- created
- reference
- sent (usd)
- received (xe)
- status

Invoices
- created
- description
- status
- amount

Transactions (I think this comes from index, so maybe we have sorting already)
- created
- hash
- from/to
- memo
- status
- amount

**Comment by annybs** [comment]
Requires https://github.com/edge/account-api/issues/176

**Comment by willgarrett64** [comment]
Possible issues:
Domains: sort by record type count - would involve adding sub query in API to get this info and sort by it why impacts efficiency.
Integrations: sort by traffic/requests - this data comes from a separate API call to `getIntegrations()` so not sure how I'd sort by this.  
Invoices: sort by description - not really necessary/possible as the description is created by UI based on the invoice dates.
